import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from './components/footer'
import {ClerkProvider, UserButton} from "@clerk/nextjs"
import Header from './components/header'
import 'sfac-designkit-react/style.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Header/>
          <hr/>
          <div className='h-auto min-h-screen'>
            {children}
          </div>
          <hr/>
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  )
}
